#!/usr/bin/env python3
"""Build the standalone Tampermonkey userscript from the Chrome manifest order."""

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "userscript" / "guiaHUD.user.js"
REPO_RAW = "https://raw.githubusercontent.com/guilhermeasmoreira/guiaHUD/main/userscript/guiaHUD.user.js"


def build():
    manifest = json.loads((ROOT / "manifest.json").read_text(encoding="utf-8"))
    scripts = manifest["content_scripts"]
    if len(scripts) != 2 or scripts[0]["js"] != ["src/render-control.js"] or scripts[0].get("world") != "MAIN":
        raise ValueError("Unexpected MAIN-world script order in manifest.json")
    if scripts[1].get("run_at") != "document_idle":
        raise ValueError("Unexpected HUD injection order in manifest.json")
    header = "\n".join([
        "// ==UserScript==",
        "// @name         guiaHUD — HUD para PokeIdle",
        "// @namespace    https://github.com/guilhermeasmoreira/guiaHUD",
        f"// @version      {manifest['version']}",
        "// @description  HUD compacta com temas e Modo Econômico para PokeIdle Online.",
        "// @match        https://pokeidle.online/game/*",
        "// @run-at       document-start",
        "// @sandbox      raw",
        "// @grant        none",
        "// @noframes",
        "// @homepageURL  https://github.com/guilhermeasmoreira/guiaHUD",
        f"// @downloadURL {REPO_RAW}",
        f"// @updateURL   {REPO_RAW}",
        "// ==/UserScript==",
        "",
        "// Generated by scripts/build-userscript.py; edit src/ and rebuild.",
        "",
    ])
    parts = [header]

    # The render hook runs first and stays in the page world, just as in the extension.
    for path in scripts[0]["js"]:
        parts.extend([f"// Source: {path}\n", (ROOT / path).read_text(encoding="utf-8"), "\n"])

    # With @grant none, Tampermonkey provides the page world but no GM storage API.
    # Keep userscript settings separate from the game's and the extension's storage.
    parts.append("""(function (global) {
  'use strict';
  const app = global.PokeClanHUD = global.PokeClanHUD || {};
  app.modules = app.modules || {};
  const prefix = 'guiaHUD.userscript.';
  app.modules.userScriptStorage = {
    get: function (key) {
      try {
        const value = global.localStorage.getItem(prefix + key);
        return value === null ? null : JSON.parse(value);
      } catch (_) { return null; }
    },
    set: function (key, value) {
      try {
        global.localStorage.setItem(prefix + key, JSON.stringify(value));
        return true;
      } catch (_) { return false; }
    }
  };
})(globalThis);

""")

    css = "\n".join((ROOT / path).read_text(encoding="utf-8") for path in scripts[1]["css"])
    parts.append("""(function (global) {
  'use strict';
  const style = global.document.createElement('style');
  style.id = 'guiahud-userscript-style';
  style.textContent = """ + json.dumps(css, ensure_ascii=False) + """;
  function mountStyle() {
    if (!style.isConnected && global.document.documentElement) {
      global.document.documentElement.append(style);
    }
  }
  mountStyle();
  if (!style.isConnected) global.document.addEventListener('DOMContentLoaded', mountStyle, { once: true });
})(globalThis);

""")
    for path in scripts[1]["js"]:
        parts.extend([f"// Source: {path}\n", (ROOT / path).read_text(encoding="utf-8"), "\n"])
    return "".join(parts)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check if the committed userscript matches sources")
    args = parser.parse_args()
    rendered = build()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            parser.error(f"{OUTPUT.relative_to(ROOT)} is stale; run python3 scripts/build-userscript.py")
        print("Userscript is up to date")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(rendered, encoding="utf-8")
        print(f"Built {OUTPUT.relative_to(ROOT)} ({len(rendered.encode('utf-8'))} bytes)")


if __name__ == "__main__":
    main()
