"""Embed editable SVG ornaments in CSS for extension and userscript portability."""
from pathlib import Path
from urllib.parse import quote
import base64
import sys

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'src/assets/themes/wingeon/ranking'
MAPPING = {
    'header-art': 'header-illustrated.webp', 'emblem': 'icon-theme.svg',
    'hall-art': 'hall-illustrated.webp', 'wings': 'wing-ornament.svg',
    'podium-silver': 'podium-left.svg', 'podium-gold': 'podium-center.svg',
    'podium-bronze': 'podium-right.svg',
}
lines = ['/* Generated by scripts/build-ranking-assets.py; edit the source SVGs. */',
         '.gh-ranking-theme-wingeon {']
for token, filename in MAPPING.items():
    if filename.endswith('.webp'):
        uri = 'data:image/webp;base64,' + base64.b64encode((ASSETS / filename).read_bytes()).decode('ascii')
    else:
        source = (ASSETS / filename).read_text(encoding='utf-8').strip()
        uri = 'data:image/svg+xml,' + quote(source, safe='')
    lines.append(f'  --gh-rk-{token}: url("{uri}");')
lines.append('}\n')
result = '\n'.join(lines)
target = ROOT / 'src/themes/ranking-wingeon-assets.css'
if '--check' in sys.argv:
    if not target.exists() or target.read_text(encoding='utf-8') != result:
        sys.exit('Ranking assets are stale. Run python3 scripts/build-ranking-assets.py')
else:
    target.write_text(result, encoding='utf-8')
print('Ranking assets OK')
